[terminal.shell]
program = "/usr/bin/zsh"

[general]
import = [
    "~/.config/alacritty/dark_plus.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_title = true
resize_increments = true
startup_mode = "Windowed"
dynamic_padding = true

[window.class]
general = "Alacritty"
instance = "Alacritty"
