#!/usr/bin/zsh

while [ 1 -eq 1 ]; do
    current_ime=$(fcitx5-remote -n)
    ime_symbol=''

    if [[ $current_ime == "keyboard-us" ]]; then
        ime_symbol='EN'
    else
        ime_symbol='中'
    fi

    echo "{\"text\": \"${ime_symbol}\"}"

    sleep 0.2
done

