[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[aws]
symbol = 'aws '
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
symbol = 'bun '
format = '\[[$symbol($version)]($style)\]'

[c]
symbol = 'C '
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
symbol = 'cmake '
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
symbol = 'cobol '
format = '\[[$symbol($version)]($style)\]'

[conda]
symbol = 'conda '
format = '\[[$symbol$environment]($style)\]'

[crystal]
symbol = 'cr '
format = '\[[$symbol($version)]($style)\]'

[daml]
symbol = 'daml '
format = '\[[$symbol($version)]($style)\]'

[dart]
symbol = 'dart '
format = '\[[$symbol($version)]($style)\]'

[deno]
symbol = 'deno '
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = ' ro'

[docker_context]
symbol = 'docker '
format = '\[[$symbol$context]($style)\]'

[dotnet]
symbol = '.NET '
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
symbol = 'erl '
format = '\[[$symbol($version)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
symbol = 'git '
format = '\[[$symbol$branch]($style)\]'

[git_commit]
tag_symbol = ' tag '

[git_status]
renamed = 'r'
deleted = 'x'
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = 'go '
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
symbol = 'guix '
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = 'hg '
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = 'java '
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = 'jl '
format = '\[[$symbol($version)]($style)\]'

[kotlin]
symbol = 'kt '
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
symbol = 'lua '
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = 'memory '
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
symbol = 'meson '
format = '\[[$symbol$project]($style)\]'

[nim]
symbol = 'nim '
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = 'nix '
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = 'node '
format = '\[[$symbol($version)]($style)\]'

[ocaml]
symbol = 'ml '
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
symbol = 'opa '
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = 'pkg '
format = '\[[$symbol$version]($style)\]'

[perl]
symbol = 'pl '
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = 'php '
format = '\[[$symbol($version)]($style)\]'

[pulumi]
symbol = 'pulumi '
format = '\[[$symbol$stack]($style)\]'

[purescript]
symbol = 'pure '
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = 'py '
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
symbol = 'raku '
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = 'rb '
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = 'rs '
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = 'scala '
format = '\[[$symbol($version)]($style)\]'

[spack]
symbol = 'spack '
format = '\[[$symbol$environment]($style)\]'

[sudo]
symbol = 'sudo'
format = '\[[as $symbol]\]'

[swift]
symbol = 'swift '
format = '\[[$symbol($version)]($style)\]'

[terraform]
symbol = 'terraform '
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = 'zig'
format = '\[[$symbol($version)]($style)\]'
